/*全局js文件*/
requirejs.config({
	paths:{
		jquery:"./lib/jquery3.1.1.min",
		jquery_ui:"./lib/jquery-ui.min",
		fullPage:"./lib/jquery.fullPage"
	}
});
requirejs(['jquery','h5'],function($,h5){
	var h5 = new h5.H5();
	h5.addPage('home')
			.addComponent({
				name:'h5_component_logo',
				type:'base',
				height:130,
				width:395,
				center:true,
				bg:'../images/face_logo.png',
				css:{opacity:0},
				animateIn:{top:100,opacity:1},
				animateOut:{top:0,opacity:0}
			})
			.addComponent({
				name:'h5_component_slogon',
				type:'base',
				height:99,
				width:365,
				center:true,
				bg:'../images/face_slogan.png',
				css:{opacity:0,top:180},
				animateIn:{left:'50%',opacity:1},
				animateOut:{left:0,opacity:0},
				delay:800
			})
			.addComponent({
				name:'h5_component_imageLeft',
				type:'base',
				height:493,
				width:370,
				center:false,
				bg:'../images/face_img_left.png',
				css:{left:-50,bottom:-50,opacity:0},
				animateIn:{left:0,bottom:0,opacity:1},
				animateOut:{left:-50,bottom:-50,opacity:0},
				delay:1000
			})
			.addComponent({
				name:'h5_component_imageRight',
				type:'base',
				height:449,
				width:276,
				center:false,
				bg:'../images/face_img_right.png',
				css:{right:-50,bottom:-50,opacity:0},
				animateIn:{right:0,bottom:0,opacity:1},
				animateOut:{right:-50,bottom:-50,opacity:0},
				delay:1000
			})
			
	   .addPage('desc')
	   		.addComponent({
	   			name:'h5_component_caption',
	   			text:"核心理念",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			name:'h5_component_text',
	   			text:"IT教育网＝只学有用的",
	   			type:'base',
	   			width:500,
	   			height:30,
	   			css:{
	   				opacity:0,
	   				textAlign:'center',
	   				color:'red',
	   				fontSize:'26px',
	   			},
	   			animateIn:{
	   				opacity:1,
	   				top:120
	   			},
	   			animateOut:{
	   				opacity:0
	   			},
	   			delay:500
	   		})
	   		.addComponent({
	   			name:'h5_component_description',
	   			type:'base',
	   			width:521,
	   			height:335,
   				text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero laudantium non consequatur suscipit ex officiis eveniet, dicta distinctio veniam sunt vitae quos expedita modi atque illo! At dolores doloremque ullam!',
	   			bg:"../images/description_bg.gif",
	   			css:{
	   				opacity:0,
	   				padding:"15px 10px 10px 10px",
	   				fontSize:'15px',
	   				lineHeight:'18px',
	   				textAlign:'justify',
	   				top:240
	   			},
	   			animateIn:{
	   				opacity:1,
	   				top:180
	   			},
	   			animateOut:{
	   				opacity:0,
	   				top:240
	   			},
	   			delay:2000
	   		})
	   		.addComponent({
	   			name:'h5_component_peoples',
	   			type:'base',
	   			width:515,
	   			height:305,
	   			bg:'../images/p1_people.png',
	   			css:{
	   				opacity:0,
	   				bottom:0
	   			},
	   			animateIn:{
	   				opacity:1,
	   				bottom:40
	   			},
	   			animateOut:{
	   				opacity:0,
	   				bottom:0
	   			},
	   			delay:1500
	   		})
	   .addPage('bar')
	   		.addComponent({
	   			name:'h5_component_caption',
	   			text:"前端开发课程",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			type:'bar',
				height:530,
				width:320,
				css:{
					top:170
				}
	   		})
	   	.addPage('verticalBar')
	   		.addComponent({
	   			name:'h5_component_caption',
	   			text:"前端开发课程",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			type:'verticalBar',
				height:600,
				width:640,
				css:{
					top:300
				}
	   		})
	   	.addPage('polyline')
	   		.addComponent({
	   			name:'h5_component_caption',
	   			text:"课程分布方向",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			text:"前端开发缺口巨大",
	   			type:'base',
	   			width:566,
	   			height:320,
	   			css:{
	   				top:150,
	   				textAlign:'center',
	   				color:'#ff7676',
	   				fontSize:'22px'
	   			}
	   		})
	   		.addComponent({
	   			type:'polyline',
				height:530,
				width:400,
				css:{
					top:260
				},
				animateIn:{
					top:220
				},
				animateOut:{
					top:260
				}
	   		})		
		.addPage('reda')
			.addComponent({
	   			name:'h5_component_caption',
	   			text:"后端开发课程",
	   			type:'base',
	   			width:566,
	   			height:320

	   		})
	   		.addComponent({
	   			type:'reda',
				height:400,
				width:400,
				css:{
	   				bottom:0,
	   			},
	   			animateIn:{
	   				bottom:150,
	   			},
	   			animateOut:{
	   				bottom:0
	   			}
	   		})
	  	.addPage('pie')
	  		.addComponent({
	   			name:'h5_component_caption',
	   			text:"移动开发课程资源",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			type:'pie',
				height:400,
				width:400,
				css:{
					top:100
				},
				animateIn:{
					top:240
				},
				animateOut:{
					top:100
				}
	   		})
	   	.addPage('point')
	   		.addComponent({
	   			name:'h5_component_caption',
	   			text:"课程难度分布",
	   			type:'base',
	   			width:566,
	   			height:320
	   		})
	   		.addComponent({
	   			name:'h5_component_point',
	   			type:'point',
	   			width:320,
	   			height:320,
	   			css:{
	   				bottom:0
	   			},
	   			animateIn:{
	   				bottom:100
	   			},
	   			animateOut:{
	   				bottom:0
	   			}
	   		})
	   	.addPage('tail')
	   		.addComponent({
	   			name:"h5_component_logo",
	   			width:359,
	   			height:129,
	   			bg:"../images/tail_logo.png",
	   			css:{
	   				top:240,
	   				opacity:0
	   			},
	   			animateIn:{
	   				opacity:1,
	   				top:210
	   			},
	   			animateOut:{
	   				opacity:0,
	   				top:240
	   			}
	   		})
	   		.addComponent({
	   			name:"h5_component_slogon",
	   			width:314,
	   			height:446,
	   			bg:"../images/tail_slogan.png",
	   			css:{
	   				top:280,
	   				opacity:0
	   			},
	   			animateIn:{
	   				opacity:1,
	   			},
	   			animateOut:{
	   				opacity:0,
	   			},
	   			delay:1500
	   		})
	   		.addComponent({
	   			name:"h5_component_share",
	   			center:false,
	   			width:128,
	   			height:120,
	   			bg:"../images/tail_share.png",
	   			css:{
	   				right:110,
	   				top:110,
	   				opacity:0
	   			},
	   			animateIn:{
	   				right:10,
	   				top:10,
	   				opacity:1,
	   			},
	   			animateOut:{
	   				right:110,
	   				top:110,
	   				opacity:0,
	   			}
	   		})
	   		.addComponent({
	   			name:"h5_component_back",
	   			width:52,
	   			height:50,
	   			bg:"../images/tail_back.png",
	   			func:{
	   				name:'click',
	   				callBack:'$.fn.fullpage.moveTo(1)'
	   			}
	   		}).loader(['http://tks2u.com:8080/resources/images/face_bg.png',
	   		'http://tks2u.com:8080/resources/images/footer.png',
	   		'http://tks2u.com:8080/resources/images/face_logo.png',
	   		'http://tks2u.com:8080/resources/images/face_slogan.png',
	   		'http://tks2u.com:8080/resources/images/face_img_left.png',
	   		'http://tks2u.com:8080/resources/images/face_img_right.png',
	   		'http://tks2u.com:8080/resources/images/page_bg.png',
	   		'http://tks2u.com:8080/resources/images/page_caption_bg.png',
	   		'http://tks2u.com:8080/resources/images/description_bg.gif',
	   		'http://tks2u.com:8080/resources/images/p1_people.png',
	   		'http://tks2u.com:8080/resources/images/tail_logo.png',
	   		'http://tks2u.com:8080/resources/images/tail_slogan.png',
	   		'http://tks2u.com:8080/resources/images/tail_share.png',
	   		'http://tks2u.com:8080/resources/images/tail_back.png']);
	   	var isArrive = true;
	   	// $(window).on('click',function(){
	   	// 	if (isArrive) {
	   	// 		$('.h5_component').trigger('onArrive');
	   	// 		isArrive = !isArrive;
	   	// 	}else{
	   	// 		$('.h5_component').trigger('onLeave');
	   	// 		isArrive = !isArrive;
	   	// 	}
	   	// })		
});